CREATE DATABASE IF NOT EXISTS Attendence_DB;
USE Attendence_DB;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    reg_no VARCHAR(50) NOT NULL,
    class VARCHAR(50) NOT NULL,
    department VARCHAR(50) NOT NULL
);
